config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :products
  resources :sales
  get "nosotros", to: "pages#nosotros"
  get "contacto", to: "pages#contacto"
  get "sold", to: "sales#sold_product"
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :photo

  belongs_to :user
  validates :name, :price, :details, presence: true

  include PgSearch::Model
  pg_search_scope :global_search,
                  against: [ :name, :details ],
                  associated_against: {
                    user: [ :email, :name ]
                  },
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :photo

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :last_name, :address, :photo])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :contacto, :nosotros ]

  def home
    @products = Product.all.first(4)
  end

  def contacto

  end

  def nosotros

  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]
  before_action :set_product, only: [ :show, :edit, :update, :destroy ]

  def index
    if params[:query].present?
      sql_query = "name ILIKE :query OR details ILIKE :query"
      @products = Product.where(sql_query, query: "%#{params[:query]}%")
    else
      @products = Product.all
    end
  end

  def show
  end

  def new
    @product = Product.new()
  end

  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id
    if @product.save
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @product.update(product_params)
    redirect_to product_path(@product)
  end

  def destroy
    @product.destroy
    redirect_to products_path, status: :see_other
  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :details, :photo)
  end

  def set_product
    @product = Product.find(params[:id])
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :new, :index, :show ]
  before_action :set_product, only: [ :create, :edit, :update, :destroy ]

  def new
    @sales = Sale.new
  end

  def index
    @sales = Sale.all
  end

  def show
  end

  def sold_product

  end

  private

  def set_product
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAuthorization</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/contacto.html.erb
<div class="about-section">
  <h1>Contacto</h1>
</div>

<div class= "container mt-5 mb-5">
  <div class="card-product">
    <%= image_tag  "/assets/Logo.png", class:"logo-navbar" %>
    <div class="container">
      <h2>Drugstore</h2>
      <p>+25 30 5678 0895</p>
      <p>contacto@drugstore.com</p>
      <p>Avenida Principal #1234, Región Metropolitana.</p>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
    <%= image_tag "https://res.cloudinary.com/drd7kavdp/image/upload/c_scale,h_450,w_1400/v1671117041/fb-distilled-spirits-filtration-pouring-wisky-header_1_d6ri5t.jpg", :height=>450, :width=>1400, :crop=>"scale" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "https://res.cloudinary.com/drd7kavdp/image/upload/c_scale,h_450,w_1400/v1671195544/img_22_jesaxj.webp", :height=>450, :width=>1400, :crop=>"scale" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "https://res.cloudinary.com/drd7kavdp/image/upload/c_scale,h_450,w_1400/v1671195085/img_19_hsqi3l.webp", :height=>450, :width=>1400, :crop=>"scale" %>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

<div class="container mt-5">
  <div class="row">
  <% @products.each do |product| %>
  <div class="col">
      <div class="card" style="box-shadow: 2px 2px 2px 1px rgba(0, 0, 0, 0.2); border-radius: 8px 8px 8px 8px;">
        <div class="text-center">
        <%= cl_image_tag product.photo.key, class:"img-card card-img-top" %>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= product.name  %> <h5><%= product.price %> ARS</h5> </h5>
          <p class="card-text ov-text"><%= product.details.truncate(100) %></p>
         <%= link_to "ver detalles" , product_path(product.id), class: "btn btn-primary"%>
        </div>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/pages/nosotros.html.erb
<div class="about-section">
  <h1>Our Team</h1>
</div>

<div class="row">

  <div class="column">
    <div class="card">
      <%= image_tag "https://res.cloudinary.com/dcakvgdsg/image/upload/v1670686966/development/0a7dwram8vikp1tb69jf6e0s2h9h.png", class:"radio-imagen" %>
      <div class="container">
        <h2>Carolina Ramirez</h2>
        <p class="title">CEO, Founder & Fullstack Dev</p>
        <p>International experience, working and learning in multicultural environments. Passionate about IT solutions. Founder of Drugstore.</p>
        <p>carolina@gmail.com</p>
      </div>
    </div>
  </div>

  <div class="column">
    <div class="card">
      <%= image_tag "https://res.cloudinary.com/dcakvgdsg/image/upload/v1670686968/development/xjt1kx3z4ok0r2py7xpvt3w7l8ma.jpg", class:"radio-imagen" %>
      <div class="container">
        <h2>Gastón Henrich</h2>
        <p class="title">Fullstack Dev</p>
        <p>Hi my name is Gaston Henrich i am 32 years old and i am from argentina currently living in australia, I am passionate ,curious about technology .</p>
        <p>gaston@gmail.com</p>
      </div>
    </div>
  </div>

  <div class="column">
    <div class="card">
      <%= image_tag "https://res.cloudinary.com/dcakvgdsg/image/upload/v1670686964/development/4n5bosu9lvxgpilbupsvff7bst0i.jpg", class:"radio-imagen" %>
      <div class="container">
        <h2>Francisco Giacci</h2>
        <p class="title">Fullstack Dev</p>
        <p>International Master in Business Administration. I am passionate about solving problems, analysing them from different perspectives.</p>
        <p>francisco@gmail.com</p>
      </div>
    </div>
  </div>

  <div class="column">
    <div class="card">
      <%= image_tag "https://res.cloudinary.com/dcakvgdsg/image/upload/v1670686962/development/e6xjmbo9d0rnqilhqha5hzixi0ay.jpg", class:"radio-imagen" %>
      <div class="container">
        <h2>Michelle Madrid</h2>
        <p class="title">Fullstack Dev</p>
        <p>Engineering student at Pontificia Universidad Católica de Chile. I like nature, watching films and going out with my friends.</p>
        <p>michelle@gmail.com</p>
      </div>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<div class="container">
<%= simple_form_for @product do |f| %>
  <%= f.input :name %>
  <%= f.input :price %>
  <%= f.input :details %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit %>
<% end %>
</div>

app/views/products/index.html.erb
<div class="container mt-5">
  <div class="row product-container">
    <% @products.each do |product| %>
          <div class="col">
            <div class="card" style="box-shadow: 2px 2px 2px 1px rgba(0, 0, 0, 0.2); border-radius: 8px 8px 8px 8px;">
              <% if product.photo.key != nil %>
                <%= cl_image_tag product.photo.key, class:"img-card card-img-top"%>
              <% end %>
              <div class="card-body">
                <h5 class="card-title" ><%= product.name.upcase %> <h5> <%= product.price %> ARS</h5></h5>
                <p class="card-text ov-text"><%= product.details %></p>
                <%= link_to "Ver detalles", product_path(product), class: "btn btn-primary mt-3" %>
              </div>
            </div>
          </div>
      <% end %>
  </div>
</div>

app/views/products/new.html.erb
<div class="container">
<%= simple_form_for @product do |f| %>
<section class="vh-400" style="background-color: white;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card shadow-2-strong" style="border-radius: 0.5rem;">
          <div class="card-body p-5 text-center " style="box-shadow: 3px 3px 3px 1px rgba(0, 0, 0, 0.4); border-radius: 8px 8px 8px 8px;">

            <h3 class="mb-5">Crear bebida</h3>

            <div class="form-outline mb-4">
            <%= f.input :name, class: "form-control form-control-lg" %>
            </div>

            <div class="form-outline mb-4">
            <%= f.input :price, class:"form-control form-control-lg" %>
            </div>

            <div class="form-outline mb-4">
            <%=  f.input :details, class: "form-control form-control-lg" %>
            </div>

            <div class="form-outline mb-4">
            <%= f.input :photo, as: :file, class: "form-control form-control-lg" %>
            </div>


              <%= f.button :submit, "Crear", class:"btn btn-primary btn-lg btn-block mt-3" %>
            <hr class="my-4">

          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<% end %>

app/views/products/show.html.erb
<div class= "container mt-5 mb-5">
  <div class="card-product">
    <%= cl_image_tag @product.photo.key, class: "imagen", height: 350, crop: :fill %>
    <div class="card-product-infos">
      <h1 style="color: black;"><%= @product.name  %></h1>
        <h2 style="color: black;"><%= @product.price  %> ARS </h2>
        <p style="color: black;"><%= @product.details %></p>
        <a href="<%= sold_path %>" class="btn btn-primary">Comprar</a>
        <div class= "card-product-infos" >

          <% if user_signed_in? %>
            <% if @product.user_id == current_user.id %>
              <%= link_to "Delete", product_path(@product), data: {turbo_method: :delete, turbo_confirm: "Estas seguro?"}, class: "btn btn-secondary" %>
              <%= link_to "Edit", edit_product_path(@product), class: "btn btn-secondary" %>
            <% end %>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/sales/create.html.erb
<h1> hola <h1>

app/views/sales/index.html.erb
<h1>hola</h1>

app/views/sales/new.html.erb
<h1> hola <h1>

app/views/sales/sold_product.html.erb
<div class="container py-5">

  <!-- For demo purpose -->
  <div class="row mb-4">
    <div class="col-lg-8 mx-auto text-center">
      <p class="lead mb-0">A continuacion ingrese los datos de su tarjeta</p>
    </div>
  </div>
  <!-- End -->


  <div class="row">
    <div class="col-lg-7 mx-auto">
      <div class="bg-white rounded-lg shadow-sm p-5">
        <!-- Credit card form tabs -->
        <ul role="tablist" class="nav bg-light nav-pills rounded-pill nav-fill mb-3">

          <li class="nav-item">
            <a data-toggle="pill" href="#nav-tab-card" class="nav-link active rounded-pill">
                                <i class="fa fa-credit-card"></i>
                                Credit Card
                            </a>
          </li>
          <li class="nav-item">
            <a data-toggle="pill" href="#nav-tab-paypal" class="nav-link rounded-pill">
                                <i class="fa fa-paypal"></i>
                                Paypal
                            </a>
          </li>
          <li class="nav-item">
            <a data-toggle="pill" href="#nav-tab-bank" class="nav-link rounded-pill">
                                <i class="fa fa-university"></i>
                                 Bank Transfer
                             </a>
          </li>
        </ul>
        <!-- End -->


        <!-- Credit card form content -->
        <div class="tab-content">

          <!-- credit card info-->
          <div id="nav-tab-card" class="tab-pane fade show active">
            <p class="alert alert-success">Some text success or error</p>
            <form role="form">
             <div class="form-group">
                <label for="username">Price to pay </label>
                <input type="text" name="username" placeholder="Jason Doe" required class="form-control">
              </div>
              <div class="form-group">
                <label for="username">Full name (on the card)</label>
                <input type="text" name="username" placeholder="Jason Doe" required class="form-control">
              </div>
              <div class="form-group">
                <label for="cardNumber">Card number</label>
                <div class="input-group">
                  <input type="text" name="cardNumber" placeholder="Your card number" class="form-control" required>
                  <div class="input-group-append">
                    <span class="input-group-text text-muted">
                                                <i class="fa fa-cc-visa mx-1"></i>
                                                <i class="fa fa-cc-amex mx-1"></i>
                                                <i class="fa fa-cc-mastercard mx-1"></i>
                                            </span>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-sm-8">
                  <div class="form-group">
                    <label><span class="hidden-xs">Expiration</span></label>
                    <div class="input-group">
                      <input type="number" placeholder="MM" name="" class="form-control" required>
                      <input type="number" placeholder="YY" name="" class="form-control" required>
                    </div>
                  </div>
                </div>
                <div class="col-sm-4">
                  <div class="form-group mb-4">
                    <label data-toggle="tooltip" title="Three-digits code on the back of your card">CVV
                                                <i class="fa fa-question-circle"></i>
                                            </label>
                    <input type="text" required class="form-control">
                  </div>
                </div>



              </div>
              <button type="button" class="subscribe btn btn-primary btn-block rounded-pill shadow-sm"> Confirm  </button>
            </form>
          </div>
          <!-- End -->

          <!-- Paypal info -->
          <div id="nav-tab-paypal" class="tab-pane fade">
            <p>Paypal is easiest way to pay online</p>
            <p>
              <button type="button" class="btn btn-primary rounded-pill"><i class="fa fa-paypal mr-2"></i> Log into my Paypal</button>
            </p>
            <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
            </p>
          </div>
          <!-- End -->

          <!-- bank transfer info -->
          <div id="nav-tab-bank" class="tab-pane fade">
            <h6>Bank account details</h6>
            <dl>
              <dt>Bank</dt>
              <dd> THE WORLD BANK</dd>
            </dl>
            <dl>
              <dt>Account number</dt>
              <dd>7775877975</dd>
            </dl>
            <dl>
              <dt>IBAN</dt>
              <dd>CZ7775877975656</dd>
            </dl>
            <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
            </p>
          </div>
          <!-- End -->
        </div>
        <!-- End -->

      </div>
    </div>
  </div>
</div>


<div style="height: 58vh">
  <div class= "container mt-5 mb-5">
    <div class="card-product">
      <div class="card-product-infos">
        <p style="text-align: center;"><strong>Su compra ha sido realizada con éxito.<br>Recibirá un email a la brevedad.<br>
        Recuerde que para retirar su producto debe presentar su identificación personal y ser mayor de 18 años.</strong></p>
        <h2 style="text-align: center;"><strong>Muchas gracias por su compra!</strong></h2>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class= "footer py-3 my-4">
        <ul class="nav justify-content-center border-bottom pb-3 mb-3">
          <%= link_to "Home", root_path, class: "nav-link px-2 text-muted" %>
          <%= link_to "Contacto", contacto_path, class: "nav-link px-2 text-muted" %>
          <%= link_to "Nosotros", nosotros_path, class: "nav-link px-2 text-muted" %>
        </ul>
        <p class="text-center text-muted">&copy; 2022 Drugstore company, Inc</p>
      </footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" style="background-color: white;">
<%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag  "/assets/logo.png", class:"logo-navbar" %>
    <% end %>
    <div class="collapse ms-auto navbar-collapse" id="navbarSupportedContent">
      <div class="container">
        <div class="buscar me-1">
          <%= form_with url: products_path, class: "d-flex", method: :get do %>
          <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Buscar Bebidas" %>
          <%= submit_tag "Buscar", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
        <%= link_to "Bebidas", products_path, class: "navbar-brand nav-link ms-5" %>
        <%= link_to "Crear Bebida", new_product_path, class: "navbar-brand nav-link" %>
        <ul class="navbar-nav me-auto">
          <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <% if current_user.photo.key %>
                <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle mx-4", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Profile", edit_user_registration_path, class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class:  "dropdown-item" %>
              </div>
              <% else %>
               <%= image_tag "alba.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Action", "#", class: "dropdown-item" %>
                <%= link_to "Another action", "#", class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
              </div>
              <% end %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link ms-3" %>
            </li>
          <% end %>
        </ul>
    </div>
</div>